version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel_app
        restart: always
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel_network
        depends_on:
            - mysql
            - redis
        env_file:
            - .env


    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        restart: always
        environment:
            MYSQL_DATABASE: laravel_db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel_network

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        restart: always
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel_network

    redis:
        image: redis:alpine
        container_name: laravel_redis
        restart: always
        ports:
            - "6379:6379"
        networks:
            - laravel_network

    mysql_test:
        image: mysql:8.0
        container_name: laravel_mysql_test
        restart: always
        environment:
            MYSQL_DATABASE: laravel_test_db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel_test_user
            MYSQL_PASSWORD: secret
        ports:
            - "3307:3306"
        networks:
            - laravel_network
        volumes:
            - mysql_test_data:/var/lib/mysql


networks:
    laravel_network:

volumes:
    mysql_data:
    mysql_test_data:

